export enum AlertType {
  HIGH_TEMPERATURE = "HIGH_TEMPERATURE",
  LOW_SOIL_MOISTURE = "LOW_SOIL_MOISTURE",
  HIGH_SOIL_MOISTURE = "HIGH_SOIL_MOISTURE",
  INVALID_WATER_FLOW = "INVALID_WATER_FLOW",
  MISSING_SENSOR_DATA = "MISSING_SENSOR_DATA",
}